/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniprojet.View;

import Controlleur.Connexion;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;


/**
 *
 * @author ahmed
 */
public class Principale extends javax.swing.JFrame {

    /**
     * Creates new form Principale
     */
    public Principale() {
        initComponents();
        new CambiaPanel(pnlPrincipale, new Acceuil());
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new rsbuttom.RSButtonMetro();
        pnlMenu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        rSButtonMetro6 = new rsbuttom.RSButtonMetro();
        rSButtonMetro7 = new rsbuttom.RSButtonMetro();
        fournir1 = new rsbuttom.RSButtonMetro();
        fournir2 = new rsbuttom.RSButtonMetro();
        rSButtonMetro8 = new rsbuttom.RSButtonMetro();
        pnlPrincipale = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(196, 18, 47));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/menu (1).png"))); // NOI18N
        btnMenu.setColorHover(new java.awt.Color(196, 18, 47));
        btnMenu.setColorNormal(new java.awt.Color(196, 18, 47));
        btnMenu.setColorPressed(new java.awt.Color(196, 18, 47));
        btnMenu.setMaximumSize(new java.awt.Dimension(97, 97));
        btnMenu.setMinimumSize(new java.awt.Dimension(97, 97));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(972, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 50));

        pnlMenu.setBackground(new java.awt.Color(70, 55, 52));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        rSButtonMetro4.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setForeground(new java.awt.Color(51, 51, 51));
        rSButtonMetro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pizza-filled-50.png"))); // NOI18N
        rSButtonMetro4.setText("Produit");
        rSButtonMetro4.setColorHover(new java.awt.Color(196, 18, 47));
        rSButtonMetro4.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setColorTextNormal(new java.awt.Color(51, 51, 51));
        rSButtonMetro4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rSButtonMetro4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro4.setIconTextGap(38);
        rSButtonMetro4.setMaximumSize(new java.awt.Dimension(161, 101));
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });

        rSButtonMetro5.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ordre-d'achat-48.png"))); // NOI18N
        rSButtonMetro5.setText("Commande");
        rSButtonMetro5.setColorHover(new java.awt.Color(196, 18, 47));
        rSButtonMetro5.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setColorTextNormal(new java.awt.Color(51, 51, 51));
        rSButtonMetro5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rSButtonMetro5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro5.setIconTextGap(25);
        rSButtonMetro5.setMaximumSize(new java.awt.Dimension(161, 101));
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });

        rSButtonMetro6.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-performance-de-ventes-48.png"))); // NOI18N
        rSButtonMetro6.setText("Revenu");
        rSButtonMetro6.setColorHover(new java.awt.Color(196, 18, 47));
        rSButtonMetro6.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setColorTextNormal(new java.awt.Color(51, 51, 51));
        rSButtonMetro6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rSButtonMetro6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro6.setIconTextGap(32);
        rSButtonMetro6.setMaximumSize(new java.awt.Dimension(161, 101));
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });

        rSButtonMetro7.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-message-60.png"))); // NOI18N
        rSButtonMetro7.setText("Email");
        rSButtonMetro7.setColorHover(new java.awt.Color(196, 18, 47));
        rSButtonMetro7.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setColorTextNormal(new java.awt.Color(51, 51, 51));
        rSButtonMetro7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rSButtonMetro7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro7.setIconTextGap(25);
        rSButtonMetro7.setMaximumSize(new java.awt.Dimension(161, 101));
        rSButtonMetro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro7ActionPerformed(evt);
            }
        });

        fournir1.setBackground(new java.awt.Color(204, 204, 204));
        fournir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-accueil-52.png"))); // NOI18N
        fournir1.setText("Acceuil");
        fournir1.setColorHover(new java.awt.Color(196, 18, 47));
        fournir1.setColorNormal(new java.awt.Color(204, 204, 204));
        fournir1.setColorTextNormal(new java.awt.Color(51, 51, 51));
        fournir1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        fournir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fournir1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        fournir1.setIconTextGap(30);
        fournir1.setMaximumSize(new java.awt.Dimension(161, 101));
        fournir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fournir1ActionPerformed(evt);
            }
        });

        fournir2.setBackground(new java.awt.Color(204, 204, 204));
        fournir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-boutique-filled-50.png"))); // NOI18N
        fournir2.setText("Point de Vente");
        fournir2.setColorHover(new java.awt.Color(196, 18, 47));
        fournir2.setColorNormal(new java.awt.Color(204, 204, 204));
        fournir2.setColorTextNormal(new java.awt.Color(51, 51, 51));
        fournir2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        fournir2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fournir2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        fournir2.setIconTextGap(15);
        fournir2.setMaximumSize(new java.awt.Dimension(161, 101));
        fournir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fournir2ActionPerformed(evt);
            }
        });

        rSButtonMetro8.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro8.setForeground(new java.awt.Color(51, 51, 51));
        rSButtonMetro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-catégorie-filled-50.png"))); // NOI18N
        rSButtonMetro8.setText("Categorie");
        rSButtonMetro8.setColorHover(new java.awt.Color(196, 18, 47));
        rSButtonMetro8.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro8.setColorTextNormal(new java.awt.Color(51, 51, 51));
        rSButtonMetro8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rSButtonMetro8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro8.setIconTextGap(38);
        rSButtonMetro8.setMaximumSize(new java.awt.Dimension(161, 101));
        rSButtonMetro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonMetro7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(fournir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fournir2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rSButtonMetro4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(rSButtonMetro6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rSButtonMetro8, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fournir1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fournir2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pnlMenu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 570));

        jPanel3.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 200, 590));

        pnlPrincipale.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipale.setLayout(new javax.swing.BoxLayout(pnlPrincipale, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(pnlPrincipale, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        int position=this.pnlMenu.getX();
        if(position>-1){
            Animacion.Animacion.mover_izquierda(0, -210, 2, 2, pnlMenu);
            
        }
        else{
            Animacion.Animacion.mover_derecha(-210, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        // TODO add your handling code here:
                        new CambiaPanel(pnlPrincipale, new VueProduit());

    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // TODO add your handling code here:
       new CambiaPanel(pnlPrincipale, new VueCommande());
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        // TODO add your handling code here:
          new CambiaPanel(pnlPrincipale, new VueRevenu());
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipale, new VueEnvoiMail());
    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void fournir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fournir1ActionPerformed
        // TODO add your handling code here:
         new CambiaPanel(pnlPrincipale, new TableauBord());
    }//GEN-LAST:event_fournir1ActionPerformed

    private void fournir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fournir2ActionPerformed
        // TODO add your handling code here:
         new CambiaPanel(pnlPrincipale, new PointDeVente() );
    }//GEN-LAST:event_fournir2ActionPerformed

    private void rSButtonMetro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro8ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipale, new VueCategorie() );
    }//GEN-LAST:event_rSButtonMetro8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnMenu;
    private rsbuttom.RSButtonMetro fournir1;
    private rsbuttom.RSButtonMetro fournir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipale;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private rsbuttom.RSButtonMetro rSButtonMetro6;
    private rsbuttom.RSButtonMetro rSButtonMetro7;
    private rsbuttom.RSButtonMetro rSButtonMetro8;
    // End of variables declaration//GEN-END:variables
}
